### ISSUE TITLE
Video orientation wrong

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#119]
When the video is recorded using the mobile phone's camera in portrait mode, it comes out " rotated", as in it is still a landscape video, but rotated to an angle.
Now, the problem is, FFMPEG interop does not seem to take this into account.

Steps to reproduce:
record a video with your camera in portrait mode.
Try rendering the video using the media stream source.
Optionally, you can query
AVDictionaryEntry *rotate_tag = av_dict_get(avFormatCtx->streams[videoStreamIndex]->metadata, "rotate", NULL, 0);
which will result in a non-null entry.

The work around I found is to expose a property which says the rotation of the video (exposed by the value of the above key), and then use a render transform in the UI to rotate accordingly.

**Comment by mcosmin222** [comment]
Ok, a rotate transform doesn't really do the trick, as it rotates the TC and in full screen it doesn't work.
However, there should be some way of signalling the rendering surface that it needs to rotate, because when I use a source type that's not a media stream source (i.e like a storage file), the media element/media player element correctly displays the video, so it has built-in rotation...

Another solution would be deriving from MediaPlayerElement, override behaviours in the template to rotate accordingly, but there SHOULD be an universal solution using the built-in controls.

**Comment by mcosmin222** [comment]
Ok, nvm, I found the fix.
I will create a pull request shortly.

**Comment by mcosmin222** [comment]
So, in order to fix this, you must do the following...
FFmpegInteropMSS::InitFFmpegContext:

```
AVDictionaryEntry *rotate_tag = av_dict_get(avFormatCtx->streams[videoStreamIndex]->metadata, "rotate", NULL, 0);
				if (rotate_tag != NULL)
				{
					rotateVideo = true;
					rotationAngle = atoi(rotate_tag->value);
				}
				else
				{
					rotateVideo = false;
				}
```


FFmpegInteropMSS::CreateVideoStreamDescriptor:
```
if (rotateVideo)
	{
		Platform::String^ example("{C380465D-2271-428C-9B83-ECEA3B4A85C1}");
		GUID rawguid;
		HRESULT hr = IIDFromString(example->Data(), &rawguid);
		if (SUCCEEDED(hr)) {
			Platform::Guid MF_MT_VIDEO_ROTATION(rawguid);
			videoProperties->Properties->Insert(MF_MT_VIDEO_ROTATION, (uint32)rotationAngle);
		}
	}
```

**Comment by khouzam** [comment]
Thanks @mcosmin222 

Looking forward to the pull request.

**Comment by mcosmin222** [comment]
Done.
