### ISSUE TITLE
NativePlatform not detected in the C# project

### ISSUE THREAD

**Issue by alexandruirimiea** [Microsoft/FFmpegInterop#13]
In the SamplesWin8.1\MediaPlayerCS project, the ffmpeg DLLs are not found due to the fact that the platform is always AnyCPU, therefore, the path to libraries are not correct:

E.g:
- Expected: ffmpeg\Build\Windows81\ARM\bin\avcodec-56.dll
- Actual: ffmpeg\Build\Windows81\bin\avcodec-56.dll

This is available for both Windwos 8.1 and Windows Phone 8.1 projects, for all ffmpeg DLLs

The CPP and JS project detect the libraries correctly.

**Comment by timotiusmargo** [comment]
Did you build the project from the command line? The MediaPlayerCS project does not have 'AnyCPU' configuration defined. I never end up with this configuration selected when opening the solution or project file before. However, I pushed an update to set the default to x86 anyway. Please let me know if you still encounter any issue. Thanks :)

**Comment by ionutdanila** [comment]
According to https://msdn.microsoft.com/en-us/library/c02as0cs.aspx, the name of the macro for "Current Project Platform" is $(Platform).

But the macro for "Currently Targeted Platform" is $(PlatformName) (according to https://msdn.microsoft.com/en-us/library/42x5kfw4.aspx).

So I believe that we need to consider PlatformName (for the entire solution) instead of Platform. I changed the code in .csproj (Windows and Windows Phone) and now the DLLs are correctly selected.
