### ISSUE TITLE
this mp4 file can't play correctly by FFmpegInterop

### ISSUE THREAD

**Issue by tigerwood** [Microsoft/FFmpegInterop#149]
this mp4 file can't play correctly by FFmpegInterop, but this file can be played by most player, inlcude movie&music, potplayer, vlc, windows media player, etc. please help me on it, thanks!
[111222.zip](https://github.com/Microsoft/FFmpegInterop/files/1139363/111222.zip)

**Comment by mcosmin222** [comment]
This actually happens on a lot of file formats.
I've noticed that some files have a broken frame or package, and FFMPEG interop simply aborts it. Other players just skip the broken frame and try the next one(s).

**Comment by tigerwood** [comment]
Then, do you have any idea can fix it on FFmpegInterop, thanks!

**Comment by khouzam** [comment]
Yes, it should be possible to skip the corrupted samples and keep going on the next ones.

**Comment by mcosmin222** [comment]
But then comes the question how can we tell if a file has too many broken samples?

**Comment by tigerwood** [comment]
And also, how can I know the frame is corrupted?

**Comment by mcosmin222** [comment]
It is explicitly handled already. There is a conscious choice to send a null sample when encountering a bad frame and that stops playback.

I think it was in MediSampleProvider. I cant check exactly where right now.

**Comment by mcosmin222** [comment]
The problem for this particular file is that H264AVCSampleProvider::WriteNALPacket fails for not having enough data.
`		// Make sure we have enough data
		if (packetSize < (index + 4))
		{
			hr = E_FAIL;
			break;
		}`

@khouzam, I am not very familiar with this codec, maybe someone else can step in?

**Comment by khouzam** [comment]
Ok, this is strange. I'm not seeing any problem with the samples in that file with the version of FFmpeg that is in the project.

It does have a start time issue, but with the Pull Request #47, the file now starts from the beginning.

With my build of FFmpeg from vcpkg, the FFmpeg MOV parser has issues and fails immediately when trying to do the initial seek. I'll see if this is fixed in a more recent version of FFmpeg.

@tigerwood, can you please try the latest master with FFmpeg set to the submodule revision in the project?

Thanks

**Comment by mcosmin222** [comment]
@khouzam , are you referring to the FFMPEG version that lies in the project file when you say it is working fine, or you say the latest version of the FFMEPG library (i.e from FFMPEG git) is that better one? I am currently using a version from around may and it fails.

**Comment by khouzam** [comment]
I've tried a few versions. 

- The current one that is in the ffmpeg submodule in the project. That one had some issues starting but it got fixed with the start offset change #47.
- The one that I had built using vcpkg. That failed to play completely, but within FFmpeg, not with the issue that you're seeing.
- I updated the ffmpeg submodule to the latest release n3.3.2 (#155) and the file played properly also.

**Comment by mcosmin222** [comment]
OK. I will update my versions too.

**Comment by khouzam** [comment]
Thanks, please validate your scenarios. I'd like to make sure that things are good and move FFmpeg up to the latest release.

**Comment by mcosmin222** [comment]
This may take a while...

**Comment by mcosmin222** [comment]
Ok the while is over.
It works fine with my mid-may FFMPEG version after merging every commit since I last updated this project.

**Comment by khouzam** [comment]
I'm going to close this issue as it looks to have been addressed. Please reopen if this is not working.
