### ISSUE TITLE
 HRESULT=0xC00D3E85  An error occurred while decoding the media resource

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#15]
I've been getting a lot of media failures with this error code lately. Sometimes the same file can work, and some other times not.

There is no extra information on this other than the error code. 

PS: only happens if i force decoding.

**Comment by mcosmin222** [comment]
After almost 2 weeks of investigations I came out with literally nothing. This seems to be completely random :(

**Comment by mcosmin222** [comment]
Well after all this time, I managed to find the answer: thread racing!
It is, technically, the media stream source implementation's fault.

How to fix? Protected the destructor and the sample request events with a mutex (std::recursive_mutex), as described here

http://social.technet.microsoft.com/wiki/contents/articles/30827.implementing-media-stream-sources-in-windows-phone-runtime-for-background-audio-tasks.aspx

Originally, I thought my own advise was not necessary anymore, because the sample request event already checks against the mss being null (destructor called). But that is not enough, as I have explained there.

So if anyone gets this weird, unexplained error message, make sure you protect the sample request and destructor with a mutex.
