### ISSUE TITLE
error while trying to bootstrap vcpkg

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/FFmpegInterop#164]
I tried the method for building with VS 2017. and I am able to complete first step of cloning the repo, but it fails in second step when I try to bootstrap. and I have the following error.  the image for error is attached. just for reference of the method I used, please see the issue #136  
![error](https://user-images.githubusercontent.com/11542189/29484492-e21b8126-8474-11e7-8c6a-b1619afd1213.png)

**Comment by ras0219-msft** [comment]
Hi @touseefbsb!

This error indicates that for the Windows SDK selected by Vcpkg (the latest one installed on your machine), you've probably only installed the UWP component, not the desktop windows component. This is most easily fixed by just launching the VS 2017 installer and ensuring that the optional component "Windows 10 SDK (10.x.y.z) for Desktop C++" is selected under the "Desktop development with C++" section on the right.

**Comment by touseefbsb** [comment]
yeah thanks that solved the problem
