### ISSUE TITLE
Clarify target platform for Windows Store Apps

### ISSUE THREAD

**Issue by fdesbrosses** [Microsoft/FFmpegInterop#18]
FFmpegInterop is exactly what I was looking for, and my first impressions are great ! 

Though, I got a question regarding the target platform for Windows Store Apps. Currently I'm using "Any Cpu", and it's not clear to me what version (*.winmd and dlls) I should import : x86 or x64 or both ? Do I have to split my app for each target ? Well, I'm a little lost there...

For Windows Phone, it's kinda obvious, it's ARM...

Thank you for your answer.

**Comment by khouzam** [comment]
I would recommend against using AnyCPU and just produce an architecture specific build of the managed or JS components. Because there are native components to be included, you still need to create a package for each target architecture.

For Windows, producing x86 and x64 are valid for most machines, some low end tablets might only be x86 but you also have ARM tablets that might want to target, such as the Surface RT and Surface 2.

For the phone, you can have only ARM but if you want to develop using the emulator then you will need to use the x86 binaries.

I hope that this is making some sort of sense.

**Comment by fdesbrosses** [comment]
Thank you it's clearer :)
