### ISSUE TITLE
WPF Support

### ISSUE THREAD

**Issue by kmcginnes** [Microsoft/FFmpegInterop#21]
TLDR; Will this library support WPF easily?

I have not had the opportunity to pull down the code and see if it just works. I assume there'll have to be slight modifications to make the code work with the full .Net library instead of the WinRT library. Any insights on whether this should be easy/hard/impossible?

**Comment by khouzam** [comment]
That is not something that we have tried, but the interop library is written in C++ and does not use .Net, so that should be much of an issue.

The main issue that you will most likely encounter is that you cannot set a MediaStreamSource on the WPF MediaElement. To counter that limitation, you should be able register the MediaStreamSource using the Media Foundation extension so that it can be invoked when setting a source as a URI on the MediaElement.

Here's a link to a sample of this.
https://code.msdn.microsoft.com/windowsapps/MediaStreamSource-media-dfd55dff
I don't know for sure that this will work, but that's the closest way that I think this could work.

**Comment by kmcginnes** [comment]
That's a great start for me. Thank you so much!

**Comment by HppZ** [comment]
>  you should be able register the MediaStreamSource using the Media Foundation extension so that it can be invoked when setting a source as a URI on the MediaElement.

@khouzam I think the sample is not relevant. it is a uwp sample. https://code.msdn.microsoft.com/windowsapps/MediaStreamSource-media-dfd55dff

**Comment by HppZ** [comment]
https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/MediaStreamSource%20streaming%20sample
