### ISSUE TITLE
Video playback buffers huge amount of data on W10M

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#97]
I noticed that this particular media stream source will buffer a huge amount of data unless hardware decoding is used.
FFMPEG decoding seems to use quite a bit of memory, around 220 on desktop, and goes OOM exception on mobile.
The issue seems to be excessive buffering: even with 0 seconds buffer time, it continues to buffer without actually playing anything. The samples are obviously not released, leading to huge memory consumption.

**Comment by khouzam** [comment]
On Desktop, I'm seeing similar behavior but reducing the buffering time does reduce the consumption. The default buffering on a MediaStreamSource is 3 seconds, which for 1080p frames can lead to a huge amount of memory. If I reduce the buffering time to 1 second, the memory goes down to about 78MB.

I'm simply setting the time like this before playing the media:

                    MediaStreamSource mss = FFmpegMSS.GetMediaStreamSource();
                    mss.BufferTime = TimeSpan.FromSeconds(1);

**Comment by mcosmin222** [comment]
78MB is still unacceptable for mobile media playback in background.
If I force hardware decoding, the memory never goes above 20-30MB with the same file and same buffer time, so there's that, an obvious problem with media stream source.

I haven't had the chance to do more experimenting with this issue lately, but I will get to it soon.

**Comment by khouzam** [comment]
The force decode option has FFmpeg do the decoding, which currently means, it will take the compressed samples and decode them while using the CPU and hand back a memory buffer that contains the data. For 1080p videos, that's 3MB per sample. Reducing the buffer size even more in the MediaStreamSource will help reduce that memory. On problem that you'll face in mobile is decoding that video resolution on the CPU. While the GPU will handle it no problem, I'm not sure that the CPU can keep up.

If you don't force video decode, then FFmpeg will take the compressed samples which are much smaller. The MediaStreamSource then buffers the compressed samples that then get decoded using the HW decoders on the GPU. The MediaPipeline will do its own buffer handling but in this case you're only handling the uncompressed buffers once.

Perhaps if you use the MediaPlayer class as mentionned in #98 and reduce the buffer size, you might reduce the memory even further.

**Comment by lukasf** [comment]
When playing local files on a PC, you can even set BufferTime to 0. Video and Audio Renderes will do buffering on their own, and playback should usually be smooth without MSS doing any buffering. MSS was primarily designed for streaming, that is why it has a very high buffer time by default. 

On a PC or even phone (with local files), I would recommend to use either 0, or if you want to be extra safe, use maybe 100ms max. That is still 2-3 frames of video and 100ms of audio, on top of the buffering that renderers have. This will give you much lower memory consumption and faster playback start and seeking.

Please be aware that a single FullHD frame will take 6MB. That alone is 150MB for one second at 25fps! Think twice before using such a huge buffer. When using 100ms, I get 180MB with force decode vs 160MB with hardware decode. That is acceptable IMO. With hardware decoding, frames are stored in GPU memory, that is why it generally uses less RAM. If I use 1 second buffer, I am at a totally unacceptable level of 350MB. But memory use is still constant, no memory leaked.

**Comment by mcosmin222** [comment]
My observations say otherwise: on PC, if you set the buffer time to 0 in media stream source, you actually get the advertised 10ms low lag between sample and rendering. On phone, this is not the same.

It is more likely that the buffering happens somewhere else, not in the "system". Maybe the inner workings of ffmpeg.

On phones, setting the buffer time to 0 has no effect (latency is roughly 5 seconds regardless of the buffertime you set). But that is most likely a bug in the media foundation (one of many, which will probably never get fixed) rather than system buffering.

**Comment by lukasf** [comment]
I was talking about playback of local files on PC, not about WP.
I know that on WP, MSS support is largely broken and buggy. But WP is dead anyways.

**Comment by mcosmin222** [comment]
Well this thread was mostly about mobile. Yes, on PC it works like you said: Kind of, except i do not think MF does any more buffering than the MSS own buffer. 

Mobile is just FUBAR.

**Comment by lukasf** [comment]
Oh okay. Yeah Mobile sucks. But it is a problem of the platform implementation and happens with all MSS. There is nothing FFmpegInterop could do about that. This makes background video playback impossible on WM with MSS (at least when software decoding).

I am pretty sure that both video and audio renderer will do some buffering, otherwise it would be impossible to get smooth playback with MSS BufferTime=0. I think you can configure the MF pipeline to use less buffering, for low latency stuff. But by default, MF uses renderer buffers big enough to allow smooth playback without any buffering on source side. For a normal media pipeline, it just does not make sense to buffer on source side. Buffering should always happen on the very end of the pipeline, where the completely decoded samples are, which can be played without any further processing.
